# Generated by Django 6.0.4 on 2026-05-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0003_reportegenerado_estatus_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegenerado',
            name='notas_reporte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
