# Generated by Django 6.0.4 on 2026-05-21 04:18

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0004_alter_reportegenerado_notas_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='gestion_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_clientes.estadodocumento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_clientes.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='estadodocumento',
            name='color',
            field=colorfield.fields.ColorField(default='#00FF00', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_clientes.cliente'),
        ),
    ]
