# Generated by Django 6.0.4 on 2026-05-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0005_alter_documento_cliente_alter_documento_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodocumento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre_tipo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
