# Generated by Django 6.0.4 on 2026-05-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0006_alter_estadodocumento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodocumento',
            name='color',
            field=models.CharField(default='#00FF00', max_length=7),
        ),
    ]
