# Generated by Django 6.0.4 on 2026-05-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0007_alter_estadodocumento_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadodocumento',
            name='color',
            field=models.CharField(blank=True, choices=[('gris', '⚪ Gris'), ('verde', '🟢 Verde'), ('amarillo', '🟡 Amarillo'), ('rojo', '🔴 Rojo')], default='gris', max_length=20),
        ),
    ]
